// Code generated by hertz generator.

package main

import (
	"fmt"

	handler "HongRay.com/mymodule/biz/handler"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/get", handler.Ping)

	r.POST("/post", handler.Post)
}
